"""
Builds data/generated/count_model_memo_evidence.json -- the numbers
docs/count_models_zinb.md needs that are NOT already in
count_model_results.json:

  1. panel descriptives + the within-state mean-variance scaling exponent,
  2. a convergence AUDIT of all 12 published 2011-2021 manuscript fits, plus
     the same audit for the 2011-2019 window against
     paper_table_params_corrected.json -- item 5 of the 2026-08-22 review: the
     `reproduces_published` guard covered only the 2021 window, so nothing
     checked that the 2019 specification re-declared here still matches
     paper_table_models_corrected.py's published output,
  3. the cross-software zero-inflation check (statsmodels FE-ZINB),
  4. what the `log(inspections)` offset removes from each window -- item 4 of
     the same review: the memo gave the offset/covariate sample gaps but never
     said WHICH rows the offset drops.

This lives in its own script (not in report_count_models.py) because it FITS
MODELS -- 24 statsmodels MixedLM refits (12 per window) plus 2
ZeroInflatedNegativeBinomialP fits, ~30 s -- whereas report_count_models.py is a
pure artifact reader that should re-render the memo in under a second.
`report_count_models.py` loads the JSON this writes; if it is missing it
delegates here once and caches.

READ-ONLY with respect to the manuscript. It reads
data/generated/paper_table_params_2021.json AND
data/generated/paper_table_params_corrected.json to check its own refits against
the published values, and writes nothing under paper_table_*.

Warnings are captured with `warnings.catch_warnings(record=True)` and STORED,
never suppressed: a module-level `warnings.filterwarnings("ignore")` is exactly
what hid the non-converged published Model 1 for as long as it did, and
discarding a captured warning record is functionally the same omission.

Run: python3 scripts/build_count_model_memo_evidence.py
Output: data/generated/count_model_memo_evidence.json
"""
import json

import numpy as np
import pandas as pd

GEN = '/Users/keshavgoel/Research/data/generated/'

MEMO_EVIDENCE_PATH = GEN + 'count_model_memo_evidence.json'

# The published 2011-2021 manuscript specification, replicated here EXACTLY as
# paper_table_models_2021.py fits it (same build_panel, same lbfgs, same REML
# default, same listwise deletion), purely to audit its convergence. Nothing in
# paper_table_* is modified or regenerated by this script.
_PUB_CUBIC = ['time', 'time2', 'time3']
_PUB_SPEND = ['SPEND_APP_z', 'SPEND_WORK_z']
_PUB_LABOR = ['lii_2017_z']
_PUB_H2A = ['h2a_per_farmworker_z', 'dol_demand_met_pct_z', 'pct_flc_z']
_PUB_COLUMNS = [
    ('inspections', 'log_inspections', _PUB_CUBIC),
    ('violations', 'log_violations', ['log_inspections'] + _PUB_CUBIC),
]
_PUB_MODELS = [
    ('M1', []),
    ('M2', _PUB_SPEND + _PUB_LABOR),
    ('M3', _PUB_SPEND + _PUB_LABOR + _PUB_H2A),
]


def _panel_descriptives(window):
    """Zero fraction, dispersion, and the within-state mean-variance scaling
    slope for each outcome in one window. The slope is the diagnostic behind
    the NB1 (2021) / NB2 (2019) reversal: NB2's variance is quadratic in the
    mean (slope ~2), NB1's is linear-in-mean with a constant multiplier
    (slope ~1)."""
    d = pd.read_csv(GEN + f'count_model_panel_{window}.csv')
    out = {}
    for dv in ('inspections', 'violations'):
        s = d[dv].dropna()
        g = d.dropna(subset=[dv]).groupby('state')[dv]
        per_state_zeros = g.apply(lambda x: int((x == 0).sum()))
        st = g.agg(['mean', 'var']).dropna()
        st = st[(st['mean'] > 0) & (st['var'] > 0)]
        slope = float(np.polyfit(np.log(st['mean']), np.log(st['var']), 1)[0])
        out[dv] = {
            'n_obs': int(len(s)), 'n_states': int(d['state'].nunique()),
            'n_zeros': int((s == 0).sum()),
            'pct_zeros': float((s == 0).mean() * 100),
            'mean': float(s.mean()), 'var': float(s.var(ddof=1)),
            'var_over_mean': float(s.var(ddof=1) / s.mean()),
            'max': float(s.max()),
            'n_states_with_a_zero': int((per_state_zeros > 0).sum()),
            'max_zero_years_in_a_state': int(per_state_zeros.max()),
            'n_states_all_zero': int(sum(
                1 for _, x in g if bool((x == 0).all()))),
            'mv_slope': slope, 'mv_slope_n_states': int(len(st)),
        }
    return out


# Which published JSON each window's audit checks itself against, and which
# script produced it. 2021 -> paper_table_models_2021.py; 2019 ->
# paper_table_models_corrected.py. Both scripts declare the SAME
# specification (cubic time, Z_SPEND + Z_LABOR at M2, + Z_H2A at M3, lbfgs,
# re_formula='~time'), verified line-for-line, which is why one audit function
# serves both.
_PUBLISHED_JSON = {
    2021: 'paper_table_params_2021.json',
    2019: 'paper_table_params_corrected.json',
}


def _audit_published_fits(window=2021):
    """Refit all 12 published manuscript fits for one window (2 outcome columns
    x M1/M2/M3 x {random slope, random-intercept-only}) with the published
    optimizer, recording each one's convergence warnings, and refit any
    non-converged one with 'cg' and 'powell'.

    This is READ-ONLY with respect to the manuscript: nothing in
    paper_table_* is touched. The point is to establish the SCOPE of the
    non-convergence finding as a measured number rather than an impression,
    and to confirm the random-intercept-only refits (the ones that produce the
    reported variance-explained block) are unaffected.

    Warnings are captured with `catch_warnings(record=True)`, never suppressed
    -- a blanket `filterwarnings('ignore')` is precisely what hid this problem
    in the published pipeline.
    """
    import re as _re
    import sys as _sys
    import warnings as _warnings

    if '/Users/keshavgoel/Research/scripts' not in _sys.path:
        _sys.path.insert(0, '/Users/keshavgoel/Research/scripts')
    from build_count_model_panel import build_panel
    from statsmodels.regression.mixed_linear_model import MixedLM
    from statsmodels.tools.sm_exceptions import ConvergenceWarning

    published = json.load(open(GEN + _PUBLISHED_JSON[window]))
    df = build_panel(window)

    def one_fit(dv, rhs, re_slope, method):
        d = df.dropna(subset=[dv] + rhs).copy()
        d['state'] = pd.Categorical(d['state'])
        kw = {'re_formula': '~time'} if re_slope else {}
        with _warnings.catch_warnings(record=True) as wrec:
            _warnings.simplefilter('always')
            res = MixedLM.from_formula(f"{dv} ~ " + " + ".join(rhs), data=d,
                                       groups=d['state'], **kw).fit(method=method)
        conv_warns = [str(w.message) for w in wrec
                      if issubclass(w.category, ConvergenceWarning)]
        grad = None
        for w in conv_warns:
            m = _re.search(r'\|grad\|\s*=\s*([0-9.eE+-]+)', w)
            if m:
                grad = float(m.group(1))
        return {
            'method': method, 'n_obs': int(len(d)),
            'n_states': int(d['state'].nunique()),
            'llf': float(res.llf),
            'sigma2_u0': float(res.cov_re.iloc[0, 0]),
            'b_log_inspections': (float(res.fe_params['log_inspections'])
                                  if 'log_inspections' in res.fe_params.index else None),
            'grad_warning': grad is not None,
            'grad_norm': grad,
            'convergence_warnings': conv_warns,
        }

    fits, affected = [], None
    for outcome, dv, base in _PUB_COLUMNS:
        for model, extra in _PUB_MODELS:
            rhs = base + extra
            for re_slope, basis, pubkey in ((True, 'random slope', 'sigma2_u0'),
                                            (False, 'random intercept', 'sigma2_u0_ri')):
                r = one_fit(dv, rhs, re_slope, 'lbfgs')
                pub_u0 = float(published[outcome][model][pubkey])
                r.update({'outcome': outcome, 'model': model, 're_basis': basis,
                          'published_sigma2_u0': pub_u0,
                          # I5: the ONLY guard that the specification re-declared in
                          # this script still matches paper_table_models_2021.py.
                          # Stored per fit so validator [7] can assert all 12 are
                          # True instead of the memo asserting it in prose.
                          'reproduces_published': bool(
                              abs(r['sigma2_u0'] - pub_u0)
                              <= 1e-6 * max(1.0, abs(pub_u0)))})
                fits.append(r)
                if r['grad_warning']:
                    alts = {m: one_fit(dv, rhs, re_slope, m) for m in ('cg', 'powell')}
                    affected = {
                        'outcome': outcome, 'model': model, 're_basis': basis,
                        'n_obs': r['n_obs'], 'n_states': r['n_states'],
                        'lbfgs': r, 'cg': alts['cg'], 'powell': alts['powell'],
                        # The inspections column has no log_inspections term,
                        # so this is None there rather than a KeyError -- the
                        # 2019 arm's affected fit IS an inspections one.
                        'published_b_log_inspections': (
                            float(published[outcome][model]['log_inspections']['b'])
                            if 'log_inspections' in published[outcome][model]
                            else None),
                        'published_sigma2_u0': float(published[outcome][model][pubkey]),
                        'published_delta_pct_ri': float(published[outcome][model]['delta_pct_ri']),
                    }
    return {
        'window': window,
        'published_json': _PUBLISHED_JSON[window],
        'n_fits': len(fits),
        'n_nonconverged': sum(1 for r in fits if r['grad_warning']),
        'n_reproduces_published': sum(1 for r in fits if r['reproduces_published']),
        'n_random_intercept': sum(1 for r in fits if r['re_basis'] == 'random intercept'),
        'n_random_intercept_nonconverged': sum(
            1 for r in fits if r['re_basis'] == 'random intercept' and r['grad_warning']),
        'fits': fits,
        'affected': affected,
    }


def _offset_drop(window):
    """What the `log(inspections)` offset removes from one window's panel.

    Item 4 of the 2026-08-22 review. `count_models_zinb.R` drops every
    `inspections == 0` row from the offset specification (the offset is
    undefined there). The memo reported the resulting N gaps but never said
    WHICH rows those are -- and if they are all zero-violation rows, the offset
    specification is systematically removing precisely the "no enforcement
    activity at all" state-years a structural-zero component exists to
    represent. That property is DERIVED here, per window, rather than asserted:
    `all_dropped_are_zero_violation` is computed, so the 2019 window is checked
    on the same footing as the 2021 one and can come out either way.
    """
    d = pd.read_csv(GEN + f'count_model_panel_{window}.csv')
    dropped = d[d['inspections'] == 0]
    zero_v = dropped[dropped['violations'] == 0]
    nan_v = dropped[dropped['violations'].isna()]
    pos_v = dropped[dropped['violations'] > 0]
    return {
        'n_rows': int(len(d)),
        'n_dropped': int(len(dropped)),
        'n_dropped_zero_violation': int(len(zero_v)),
        'n_dropped_violations_missing': int(len(nan_v)),
        'n_dropped_violations_positive': int(len(pos_v)),
        'all_dropped_are_zero_violation': bool(
            len(dropped) > 0 and len(zero_v) == len(dropped)),
        'dropped_state_years': [f"{r.state}-{int(r.year)}"
                                for r in dropped.itertuples()],
        'n_zero_violation_rows': int((d['violations'] == 0).sum()),
        'pct_zero_violation_rows_dropped': (
            float(100.0 * len(zero_v) / (d['violations'] == 0).sum())
            if (d['violations'] == 0).sum() else float('nan')),
    }


def _zi_crosscheck(raw):
    """Independent cross-software check on the zero-inflation component: a
    statsmodels ZeroInflatedNegativeBinomialP with state FIXED effects (dummy
    variables) instead of glmmTMB's random effects. Different package,
    different treatment of the state dimension -- which is the whole point.

    The six M3 covariates are omitted (most are state-time-invariant and
    therefore collinear with the state dummies used here in place of a random
    intercept), so this runs on the FULL 2021 panel and retains AK/RI/VT,
    which glmmTMB's M3 drops for missing BLS applicator data. The two N's
    legitimately differ; both are recorded so the memo can report both.
    """
    import warnings as _warnings

    import statsmodels.api as sm
    from statsmodels.discrete.count_model import ZeroInflatedNegativeBinomialP

    d = pd.read_csv(GEN + 'count_model_panel_2021.csv')
    specs = {
        'insp_2021': ('inspections', [], 'insp_2021__M3__zinb'),
        'viol_cov_2021': ('violations', ['log_inspections'], 'viol_cov_2021__M3__zinb'),
    }
    out = {}
    for cell, (dv, extra, glmm_key) in specs.items():
        need = [dv, 'time', 'time2', 'time3'] + extra
        dd = d.dropna(subset=need).copy()
        X = pd.concat([dd[['time', 'time2', 'time3'] + extra],
                       pd.get_dummies(dd['state'], prefix='st',
                                      drop_first=True, dtype=float)], axis=1)
        X = sm.add_constant(X)
        # The record is CAPTURED AND STORED, not discarded: opening
        # catch_warnings(record=True) and dropping the list is functionally the
        # same omission as filterwarnings('ignore'), which is the idiom this
        # whole finding is about.
        with _warnings.catch_warnings(record=True) as wrec:
            _warnings.simplefilter('always')
            res = ZeroInflatedNegativeBinomialP(
                dd[dv], X, exog_infl=np.ones((len(dd), 1)), p=2
            ).fit(method='bfgs', maxiter=500, disp=0)
        # BOUNDED summary, not the raw list: the diverging violations fit emits
        # ~21k RuntimeWarnings, which would make this artifact ~1 MB of noise.
        # Nothing is DISCARDED silently -- the total, the per-category counts and
        # a distinct-message sample are all stored, so a new warning class can
        # never appear without showing up here.
        from collections import Counter
        warn_msgs = [f"{w.category.__name__}: {w.message}" for w in wrec]
        cat_counts = dict(Counter(m.split(':')[0] for m in warn_msgs))
        distinct = list(dict.fromkeys(warn_msgs))
        conv_warn_msgs = [m for m in distinct if 'ConvergenceWarning' in m]
        g = raw.get(glmm_key, {})
        gzi = (g.get('zi') or {}).get('(Intercept)', {})
        per_state_zeros = dd.groupby('state')[dv].apply(lambda x: int((x == 0).sum()))
        out[cell] = {
            'dv': dv, 'n_obs': int(len(dd)),
            'n_params': int(X.shape[1]),
            'design_full_rank': bool(np.linalg.matrix_rank(X.values.astype(float))
                                     == X.shape[1]),
            'converged': bool(res.mle_retvals.get('converged')),
            'n_warnings': len(warn_msgs),
            'n_distinct_warnings': len(distinct),
            'warning_categories': sorted(cat_counts),
            'warning_counts': cat_counts,
            'warnings_sample': distinct[:8],
            'convergence_warnings': conv_warn_msgs,
            'zi_b': float(res.params['inflate_const']),
            'zi_se': float(res.bse['inflate_const']),
            'intercept': float(res.params['const']),
            'alpha': float(res.params['alpha']),
            'glmm_key': glmm_key,
            'glmm_n_obs': g.get('n_obs'),
            'glmm_re_tier': g.get('re_tier'),
            'glmm_zi_b': gzi.get('b'), 'glmm_zi_se': gzi.get('se'),
            'glmm_zi_p': gzi.get('p'),
            'obs_zeros': int((dd[dv] == 0).sum()),
            'n_states_with_a_zero': int((per_state_zeros > 0).sum()),
            'max_zero_years_in_a_state': int(per_state_zeros.max()),
            'n_states_all_zero': int(sum(
                1 for _, x in dd.groupby('state')[dv] if bool((x == 0).all()))),
        }
    return out


def build_memo_evidence(raw):
    """Compute (and persist) the evidence the memo needs that is NOT already in
    count_model_results.json: panel descriptives, the convergence audit of the
    12 published 2011-2021 fits, and the cross-software ZI check. Written to
    its own artifact so validate_count_models.py [7] can check the memo's
    numbers against it independently of the prose."""
    ev = {
        'panel': {w: _panel_descriptives(w) for w in ('2019', '2021')},
        # `published_audit` stays the 2021 arm (the window the non-convergence
        # finding is about, and the one the memo's audit table reports).
        # `published_audit_2019` is the parity arm added by item 5.
        'published_audit': _audit_published_fits(2021),
        'published_audit_2019': _audit_published_fits(2019),
        'zi_crosscheck': _zi_crosscheck(raw),
        'offset_drop': {str(w): _offset_drop(w) for w in (2019, 2021)},
    }
    with open(MEMO_EVIDENCE_PATH, 'w') as fh:
        json.dump(ev, fh, indent=1)
    print(f"Wrote {MEMO_EVIDENCE_PATH}")
    return ev


def main():
    raw = json.load(open(GEN + 'count_model_results.json'))
    ev = build_memo_evidence(raw)
    for label in ('published_audit', 'published_audit_2019'):
        aud = ev[label]
        print(f"  published-fit audit [{aud['window']}, "
              f"{aud['published_json']}]: {aud['n_fits']} fits, "
              f"{aud['n_nonconverged']} with a gradient failure, "
              f"{sum(1 for r in aud['fits'] if r['reproduces_published'])} "
              f"reproducing the published sigma^2_u0")
    for w, od in sorted(ev['offset_drop'].items()):
        print(f"  offset drops {od['n_dropped']} of {od['n_rows']} rows in "
              f"{w}; all zero-violation: "
              f"{od['all_dropped_are_zero_violation']} "
              f"({od['n_dropped_zero_violation']} zero, "
              f"{od['n_dropped_violations_positive']} positive, "
              f"{od['n_dropped_violations_missing']} missing)")
    for cell, x in ev['zi_crosscheck'].items():
        print(f"  ZI cross-check {cell}: N={x['n_obs']}, "
              f"converged={x['converged']}, ZI intercept {x['zi_b']:+.4f} "
              f"(SE {x['zi_se']:.4f}), warnings={x['warning_categories']}")


if __name__ == '__main__':
    main()
