"""
Reporter for the Jafari-aligned crossed random-effects count models.

A PURE ARTIFACT READER. It fits nothing. Every derived number in this arm --
every tally, percentage and marginal probability -- is computed here and
nowhere else, so exactly one script owns each. validate_jafari_crossed.py
re-derives them independently, which is what makes that validator non-circular.

docs/jafari_crossed_models.md is GENERATED by this script. Never hand-edit it;
re-run this instead.

Run: python3 scripts/report_jafari_crossed.py
Spec: docs/superpowers/specs/2026-09-10-jafari-crossed-re-design.md
"""
import json

import numpy as np
import pandas as pd
from scipy.special import expit
from scipy.stats import norm

GEN = '/Users/keshavgoel/Research/data/generated/'
DOCS = '/Users/keshavgoel/Research/docs/'
RESULTS = GEN + 'jafari_crossed_results.json'

CELLS = ('insp_2019', 'insp_2021', 'viol_2019', 'viol_2021')
FAMILIES = ('poisson', 'nbinom1', 'nbinom2', 'zip',
            'zinb1', 'zinb2', 'zinb1_re', 'zinb2_re')
ZI_FAMILIES = ('zip', 'zinb1', 'zinb2', 'zinb1_re', 'zinb2_re')
PLAIN_FAMILIES = ('poisson', 'nbinom1', 'nbinom2')
COUNTERPART = {'zip': 'poisson', 'zinb1': 'nbinom1', 'zinb2': 'nbinom2',
               'zinb1_re': 'nbinom1', 'zinb2_re': 'nbinom2'}

FAMILY_LABEL = {'poisson': 'Poisson', 'nbinom1': 'NB1', 'nbinom2': 'NB2',
                'zip': 'ZIP', 'zinb1': 'ZI-NB1', 'zinb2': 'ZI-NB2',
                'zinb1_re': 'ZI-NB1 + ZI-RE', 'zinb2_re': 'ZI-NB2 + ZI-RE'}

CELL_LABEL = {'insp_2019': 'Inspections, 2011-2019 (establishments view)',
              'insp_2021': 'Inspections, 2011-2021 (WPS view)',
              'viol_2019': 'Violations, 2011-2019 (establishments view)',
              'viol_2021': 'Violations, 2011-2021 (WPS view)'}

TERM_LABEL = {
    '(Intercept)': 'Intercept',
    'log_inspections': 'log Inspections',
    'time': 'time', 'time2': 'time²', 'time3': 'time³',
    'SPEND_APP_z': 'STAG $ per applicator (z)',
    'SPEND_WORK_z': 'STAG $ per farmworker (z)',
    'lii_2017_z': 'Labor intensity index 2017 (z)',
    'h2a_per_farmworker_z': 'H-2A per farmworker (z)',
    'dol_demand_met_pct_z': 'DOL demand met % (z)',
    'pct_flc_z': '% farm labor contractor (z)',
}

ZI_TIER_LABEL = {
    'mirror': 'full mirror (every conditional predictor)',
    'covariates': 'covariates only (no time terms)',
    'reduced': 'spending + labor intensity',
    'intercept': 'intercept only',
}

GH_NODES = 240
GH_CONVERGENCE_TOL = 1e-4
ZI_TAIL_THRESHOLD = 0.10


def load():
    with open(RESULTS) as fh:
        return json.load(fh)


def stars(p):
    if p is None or not np.isfinite(p):
        return ''
    return '***' if p < .001 else '**' if p < .01 else '*' if p < .05 else '+' if p < .10 else ''


def zi_marginal_prob(b0, sigma2, n_nodes=GH_NODES):
    """E[plogis(b0 + u)] with u ~ N(0, sigma2), by Gauss-Hermite quadrature.

    This is the MARGINAL structural-zero probability of a ZI component that
    carries a state random intercept. `plogis(b0)` is a DIFFERENT quantity --
    the probability at a median state, u = 0 -- and with a large sigma2 the two
    are not close: plogis() is strictly convex in the far-left tail, so
    averaging over u pulls the marginal above the median-state value, by orders
    of magnitude when |b0| and sigma are both large. In the previous arm the
    two differed by a factor of ~835 in the headline cell, and reporting
    plogis(b0) as if marginal would have led a reader to conclude the
    zero-inflation was negligible. Stopping that is what this function is for.
    """
    sd = float(np.sqrt(sigma2))

    def _rule(n):
        x, w = np.polynomial.hermite.hermgauss(n)
        return float(np.sum(w * expit(b0 + np.sqrt(2.0) * sd * x)) / np.sqrt(np.pi))

    fine, coarse = _rule(n_nodes), _rule(max(4, n_nodes // 2))
    if abs(fine - coarse) > GH_CONVERGENCE_TOL * max(abs(fine), 1e-300):
        raise ValueError(
            f'Gauss-Hermite quadrature has not converged for b0={b0!r}, '
            f'sigma2={sigma2!r}: {n_nodes} nodes give {fine!r}, {n_nodes // 2} '
            f'give {coarse!r}. Raising rather than returning a silently '
            f'inaccurate marginal probability.')
    return fine


def selection_table(r):
    """One row per (cell, model, family) ladder fit. Excludes M2 and Gaussian."""
    rows = []
    for cell in CELLS:
        meta = r[f'{cell}__meta']
        for model in ('M1', 'M3'):
            fits = {f: r[f'{cell}__{model}__{f}'] for f in FAMILIES}
            winner = meta['m1_winner'] if model == 'M1' else meta['m3_winner']
            win_aic = fits[winner]['aic'] if fits[winner].get('converged') else None
            for f in FAMILIES:
                v = fits[f]
                aic = v.get('aic') if v.get('converged') else None
                rows.append({
                    'cell': cell, 'window': v['window'], 'outcome': v['outcome'],
                    'model': model, 'family': f, 'family_label': FAMILY_LABEL[f],
                    'converged': bool(v.get('converged')),
                    'zi_tier_reached': v.get('zi_tier_reached'),
                    'zi_degenerate': bool(v.get('zi_degenerate')),
                    'zi_degenerate_reason': v.get('zi_degenerate_reason') or '',
                    'collapsed_to': v.get('collapsed_to') or '',
                    'eligible': bool(v.get('eligible_for_selection')),
                    'n_obs': v.get('n_obs'), 'n_states': v.get('n_states'),
                    'n_years': v.get('n_years'),
                    'aic': aic, 'bic': v.get('bic') if v.get('converged') else None,
                    'loglik': v.get('loglik') if v.get('converged') else None,
                    'df': v.get('df'),
                    'delta_aic_to_winner': (None if aic is None or win_aic is None
                                            else aic - win_aic),
                    'is_winner': bool(v.get('is_winner')),
                    'obs_zeros': v.get('obs_zeros'), 'exp_zeros': v.get('exp_zeros'),
                    'exp_zeros_se': v.get('exp_zeros_se'),
                    'message': v.get('message') or '',
                })
    return pd.DataFrame(rows)


def coefficient_table(r):
    """Both blocks, long form. `block` is 'conditional' or 'zero_inflated'."""
    rows = []
    for cell in CELLS:
        meta = r[f'{cell}__meta']
        for model in ('M1', 'M2', 'M3'):
            fam = meta['m1_winner'] if model == 'M1' else meta['m3_winner']
            v = r.get(f'{cell}__{model}__{fam}')
            if v is None or not v.get('converged'):
                continue
            for block, terms in (('conditional', v.get('cond') or {}),
                                 ('zero_inflated', v.get('zi') or {})):
                for term, est in terms.items():
                    rows.append({
                        'cell': cell, 'window': v['window'], 'outcome': v['outcome'],
                        'model': model, 'family': fam,
                        'zi_tier_reached': v.get('zi_tier_reached'),
                        'block': block, 'term': term,
                        'label': TERM_LABEL.get(term, term),
                        'b': est['b'], 'se': est['se'], 'z': est['z'], 'p': est['p'],
                        'stars': stars(est['p']),
                        # exp(b) means a DIFFERENT thing in each block, so the two
                        # live in separate columns and are never merged: an
                        # incidence rate ratio on the expected count, versus an
                        # odds ratio on being a structural zero. Both are null on
                        # the intercept rows, where exp(b) is a baseline level and
                        # not a ratio at all (see the memo's "How to read" note).
                        'irr': (float(np.exp(est['b']))
                                if block == 'conditional' and term != '(Intercept)'
                                else None),
                        'odds_ratio': (float(np.exp(est['b']))
                                       if block == 'zero_inflated' and term != '(Intercept)'
                                       else None),
                    })
    return pd.DataFrame(rows)


def variance_table(r):
    """Variance components for each cell's selected M3 model.

    Reports BOTH structural-zero probabilities where a ZI random intercept
    exists, each explicitly labelled. Reporting only plogis(b0) is the defect
    this column set exists to prevent.
    """
    rows = []
    for cell in CELLS:
        meta = r[f'{cell}__meta']
        fam = meta['m3_winner']
        v = r[f'{cell}__M3__{fam}']
        if not v.get('converged'):
            continue
        zi_int = (v.get('zi') or {}).get('(Intercept)')
        s2_zi = v.get('sigma2_zi_state')
        tier = v.get('zi_tier_reached')
        # The intercept-based quantities answer "what is P(structural zero) for
        # a state whose ZI covariates are all ZERO". That is the whole story
        # ONLY when the ZI block is intercept-only. Once it carries the mirror,
        # x = 0 is far outside the data -- log_inspections averages ~3.5 and is
        # never z-scored -- and plogis(b0) / the GH marginal become a quantity
        # about no state in the sample. They are therefore computed only at the
        # `intercept` tier and left null elsewhere, rather than reported with a
        # caveat a reader might skip.
        med = marg = tail = None
        if zi_int is not None and tier == 'intercept':
            med = float(expit(zi_int['b']))
            if s2_zi is not None and np.isfinite(s2_zi) and s2_zi > 0:
                marg = zi_marginal_prob(zi_int['b'], s2_zi)
                # Descriptive only: share of the fitted state distribution above
                # a structural-zero probability of 0.10. A reporting convention,
                # not an inference.
                cut = (np.log(ZI_TAIL_THRESHOLD / (1 - ZI_TAIL_THRESHOLD))
                       - zi_int['b']) / np.sqrt(s2_zi)
                tail = float(norm.sf(cut))
            else:
                marg = med
        blups = v.get('year_blups') or {}
        rows.append({
            'cell': cell, 'window': v['window'], 'outcome': v['outcome'],
            'family': fam, 'family_label': FAMILY_LABEL[fam],
            'zi_tier_reached': v.get('zi_tier_reached'),
            'sigma2_state': v.get('sigma2_state'),
            'sigma2_year': v.get('sigma2_year'),
            'sigma2_zi_state': s2_zi,
            'dispersion': v.get('dispersion'), 'family_name': v.get('family_name'),
            # NULL for every count fit by design: sigma() is theta for NB2 and a
            # dispersion multiplier for NB1, so its square is not a variance.
            'sigma2_e': v.get('sigma2_e'),
            # PRIMARY: sample mean of the per-observation ZI probability,
            # conditional on the fitted random effects. Valid at every tier.
            'pr_structural_zero_sample_mean': v.get('zi_prob_mean'),
            # Intercept-tier only (see above); null when the ZI block carries
            # covariates, because then they describe no state in the sample.
            'pr_structural_zero_median_state': med,
            'pr_structural_zero_marginal': marg,
            'pct_states_above_0.10': tail,
            'obs_zeros': v.get('obs_zeros'), 'exp_zeros': v.get('exp_zeros'),
            'exp_zeros_se': v.get('exp_zeros_se'),
            'year_blup_2020': blups.get('2020'), 'year_blup_2021': blups.get('2021'),
            'n_obs': v.get('n_obs'), 'n_states': v.get('n_states'),
            'n_years': v.get('n_years'),
        })
    return pd.DataFrame(rows)



def zi_strength_tally(r):
    """Matched ZI-vs-plain comparisons -- the directive-2 deliverable.

    A comparison is MATCHED when both fits share the same cell, model and
    analytic sample, both converged, and neither is ZI-degenerate or collapsed.
    Unmatched pairs are excluded rather than reported with a caveat: an AIC
    margin between fits on different samples is not a margin at all.

    Unlike the previous arm, ZI-NB1 rungs exist, so an NB1 win is now tested
    against its own zero-inflated counterpart instead of winning by default.
    """
    rows = []
    for cell in CELLS:
        for model in ('M1', 'M3'):
            fits = {f: r[f'{cell}__{model}__{f}'] for f in FAMILIES}
            for zf in ZI_FAMILIES:
                z = fits[zf]
                if not (z.get('converged') and not z.get('zi_degenerate')
                        and not z.get('collapsed_to')):
                    continue
                for pf in PLAIN_FAMILIES:
                    p = fits[pf]
                    if not p.get('converged'):
                        continue
                    if z.get('n_obs') != p.get('n_obs'):
                        continue
                    rows.append({
                        'cell': cell, 'model': model,
                        'zi_family': zf, 'zi_family_label': FAMILY_LABEL[zf],
                        'plain_family': pf, 'plain_family_label': FAMILY_LABEL[pf],
                        'is_own_counterpart': COUNTERPART[zf] == pf,
                        'zi_tier_reached': z.get('zi_tier_reached'),
                        'n_obs': z['n_obs'],
                        'aic_zi': z['aic'], 'aic_plain': p['aic'],
                        'margin': p['aic'] - z['aic'],   # positive = ZI wins
                        'zi_wins': p['aic'] > z['aic'],
                    })
    return pd.DataFrame(rows)


def _fmt(b, se, p):
    return f'{b:.4f} ({se:.4f}){stars(p)}', f'{p:.3g}'


def _fmt_exp(b, term):
    """exp(b) for the printed tables, or an em dash where it is not a ratio.

    The intercept is deliberately NOT exponentiated. exp(intercept) is a
    baseline count (conditional block) or baseline odds (zero-inflation block)
    at the point where EVERY predictor is zero -- which for these models
    includes `log Inspections = 0`, a state-year with a single inspection, a
    point no state in the sample occupies. Printing it in a column headed IRR /
    OR would invite exactly the ratio misreading this column exists to prevent,
    so both blocks get an em dash there, consistently.
    """
    if term == '(Intercept)':
        return '—'
    v = float(np.exp(b))
    if not np.isfinite(v):
        return '—'
    if v != 0 and (v >= 1000 or v < 0.001):
        return f'{v:.2e}'
    return f'{v:.3f}'


COND_BLOCK_HEADER = (
    '| **CONDITIONAL (count) model** — expected COUNT, given the state-year is '
    'NOT a structural zero | | exp(b) = **IRR** | |')
ZI_BLOCK_HEADER = (
    '| **ZERO-INFLATION model** — log-odds that a state-year is a **STRUCTURAL '
    'ZERO**; positive b = MORE zeros = FEWER events | | exp(b) = **OR** | |')


def jafari_table(r, cell):
    """One cell's selected M3 model in Jafari et al. Table 5 two-block layout.

    Rows the reached ZI tier did not include are rendered as an em dash, so the
    table never implies a term was estimated at zero when it was simply absent
    from the ZI formula.

    Each block carries a self-describing header row and its own effect-size
    column label (IRR for the count block, OR for the zero-inflation block).
    The bare labels "Conditional Model" / "Zero-inflated Model" were read
    backwards in the 2026-09-11 team meeting -- the conditional block was taken
    for the model of the zeros -- and the raw coefficients were read as if they
    were already ratios. Both readings invert the finding, so the table states
    the estimand and prints the exponentiated value itself.
    """
    meta = r[f'{cell}__meta']
    fam = meta['m3_winner']
    v = r[f'{cell}__M3__{fam}']
    if not v.get('converged'):
        return f'\n### {CELL_LABEL[cell]}\n\nNo converged model at Model 3.\n'

    cond = v.get('cond') or {}
    zi = v.get('zi') or {}
    tier = v.get('zi_tier_reached')
    order = ['(Intercept)'] + [t for t in cond if t != '(Intercept)']

    out = [f'\n### {CELL_LABEL[cell]}', '',
           f'**Selected family:** {FAMILY_LABEL[fam]} &nbsp;&nbsp; '
           f'**Zero-inflation component:** {ZI_TIER_LABEL.get(tier, "none")} &nbsp;&nbsp; '
           f'N = {v["n_obs"]} ({v["n_states"]} states x {v["n_years"]} years)', '',
           '| Factor | b (SE) | exp(b) | Pr(>\\|z\\|) |', '|---|---:|---:|---:|',
           COND_BLOCK_HEADER]
    for t in order:
        e = cond[t]
        est, pv = _fmt(e['b'], e['se'], e['p'])
        out.append(f'| {TERM_LABEL.get(t, t)} | {est} | {_fmt_exp(e["b"], t)} | {pv} |')
    if zi:
        out.append(ZI_BLOCK_HEADER)
        for t in order:
            if t in zi:
                e = zi[t]
                est, pv = _fmt(e['b'], e['se'], e['p'])
                out.append(f'| {TERM_LABEL.get(t, t)} | {est} '
                           f'| {_fmt_exp(e["b"], t)} | {pv} |')
            else:
                out.append(f'| {TERM_LABEL.get(t, t)} | — | — | — |')
    else:
        out.append('| **ZERO-INFLATION model** — log-odds that a state-year is a '
                   '**STRUCTURAL ZERO** | not estimated (a plain count family was '
                   'selected for this cell) | | |')
    out.append('')
    return '\n'.join(out)


def _pick(r, cell, model, block, term):
    """One coefficient from a cell's selected model, or None if it is absent.

    The worked example in the "How to read" section quotes real numbers, so it
    reads them out of the artifact rather than carrying typed copies that could
    drift away from the tables printed 40 lines below them.
    """
    meta = r[f'{cell}__meta']
    fam = meta['m1_winner'] if model == 'M1' else meta['m3_winner']
    v = r.get(f'{cell}__{model}__{fam}')
    if v is None or not v.get('converged'):
        return None
    return (v.get('cond' if block == 'conditional' else 'zi') or {}).get(term)


def how_to_read(r):
    """The block-reading guide, immediately before the first Model 3 table.

    Written because two specific misreadings actually happened in the
    2026-09-11 team meeting and were about to reach a results section: the two
    blocks were swapped, and raw logit coefficients were quoted as risk ratios.
    The worked example is the exact number that was misread.
    """
    zi_app = _pick(r, 'insp_2021', 'M3', 'zero_inflated', 'SPEND_APP_z')
    cond_app = _pick(r, 'insp_2021', 'M3', 'conditional', 'SPEND_APP_z')
    cond_h2a = _pick(r, 'insp_2021', 'M3', 'conditional', 'h2a_per_farmworker_z')
    zi_h2a = _pick(r, 'insp_2021', 'M3', 'zero_inflated', 'h2a_per_farmworker_z')

    out = ["""
## How to read these two blocks

**Read this before quoting any number from the tables below.** Every
zero-inflated model here has **two** blocks. `glmmTMB` estimates them
**jointly, in one likelihood** -- they are not two separate models run one
after the other -- but they answer **different questions**, and reading either
one as the other reverses the finding.

- **Conditional (count) model. This is the COUNT model, NOT the model of the
  zeros.** It gives the expected number of inspections (or violations) in a
  state-year, *given that the state-year is not a structural zero*. A
  **positive** coefficient means **MORE** events.
- **Zero-inflation model. This is the model of the zeros.** It is a logistic
  regression for whether a state-year is a **structural zero** -- a state-year
  that was never at risk of producing a count at all. A **positive** coefficient
  means **MORE structural zeros**, and therefore **FEWER** events. That is the
  **opposite** sign direction from a positive conditional coefficient.

**The `b (SE)` column holds raw coefficients, not ratios.** They are on the log
scale in the conditional block and on the logit scale in the zero-inflation
block. The `exp(b)` column converts them -- and the conversion means a different
thing in each block:

- conditional block: `exp(b)` is an **incidence rate ratio (IRR)**, the
  multiplicative change in the expected **count** per 1-unit increase in the
  predictor (per **1 SD**, for every variable marked `(z)`);
- zero-inflation block: `exp(b)` is an **odds ratio (OR)**, the multiplicative
  change in the **odds that the state-year is a structural zero**.

An IRR and an OR are **not interchangeable**, and neither may be quoted as the
other. An OR above 1 in the zero-inflation block is a *reduction* in enforcement
activity, not an increase. `exp(b)` is left as an em dash on the **intercept**
rows of both blocks: the intercept is a baseline level, not a ratio, and
exponentiating it describes a state-year with every predictor at zero --
including `log Inspections = 0` -- which no state in the sample is.
"""]

    if zi_app is not None:
        b = zi_app['b']
        lines = [
            '\n### Worked example, using the number that was misread\n',
            f'In **{CELL_LABEL["insp_2021"]}**, the **zero-inflation** block gives '
            f'`STAG $ per applicator (z)` **b = {b:.4f}** (p = {zi_app["p"]:.3g}). '
            f'That is a logit coefficient, so **OR = exp({b:.4f}) = '
            f'{float(np.exp(b)):.2f}**.\n',
            f'> A 1-SD increase in STAG spending per pesticide applicator is '
            f'associated with about **{float(np.exp(b)):.1f} times the odds that a '
            f'state-year is a structural zero for inspections** -- that is, with '
            f'**FEWER** inspections, not more.\n',
            f'Reading the raw `{b:.4f}` as though it were already a ratio -- which '
            f'would suggest a change of about {100 * (b - 1):.0f}% -- is wrong twice '
            f'over: it treats a coefficient as a ratio, and it treats the '
            f'zero-inflation block as if it were the count block. The direction comes '
            f'out backwards.\n',
        ]
        if cond_app is not None:
            lines.append(
                f'In the **conditional** block of that same cell the same predictor '
                f'is **b = {cond_app["b"]:.4f}** (IRR = {float(np.exp(cond_app["b"])):.3f}, '
                f'p = {cond_app["p"]:.3g}) -- no detectable association with the '
                f'inspection count.\n')
        if cond_h2a is not None and zi_h2a is not None:
            lines.append(
                f'The same care applies to `H-2A per farmworker (z)` in this cell. It '
                f'is **b = {cond_h2a["b"]:+.4f}, p = {cond_h2a["p"]:.3g}, in the '
                f'CONDITIONAL (count) block** -- IRR = '
                f'{float(np.exp(cond_h2a["b"])):.3f}, i.e. **more inspections**. In '
                f'the zero-inflation block it is {zi_h2a["b"]:.4f} and **not** '
                f'significant (p = {zi_h2a["p"]:.3g}), so it says nothing about '
                f'structural zeros. It is a finding about inspection **counts**, '
                f'not about zeros.\n')
        out.append('\n'.join(lines))
    return '\n'.join(out)


MEMO_HEADER = """# Jafari-aligned crossed random-effects count models

**GENERATED by `scripts/report_jafari_crossed.py`. Never hand-edit -- re-run it.**

**Spec:** `docs/superpowers/specs/2026-09-10-jafari-crossed-re-design.md`

Replicates the model class of Jafari et al. (*PLOS ONE* 2024,
doi:10.1371/journal.pone.0302960) under three PI directives of 2026-09-10:
random intercepts only; crossed random effects of **state** and **year**
(substituting time for Jafari's industry dimension, which this project has no
analogue for); and a best-fitting family chosen **independently per outcome**,
with no symmetry constraint. The zero-inflation component carries the same
predictors as the conditional component wherever that is estimable, and both
blocks are reported.

`glmmTMB` already estimated the two components in one joint likelihood, and
always did -- that part always matched Jafari. What differed was that the
previous ladder set `ziformula = ~1` where Jafari mirrors the full predictor
list, and that its reporter never printed a zero-inflation block. Both are
closed here; no new estimation machinery was required.

## What this arm is NOT comparable to

- **Not comparable to `docs/count_models_zinb.md`.** That arm mandates
  `(1 + time | state)`. These fixed effects are conditional on a different
  partition of the variance, so coefficients are not line-by-line comparable.
  Any comparison must name which arm it quotes.
- **Not comparable in magnitude to the published Tables 2/3.** Variance
  components here are on the **log link** scale; the published tables are on the
  `log(count + 1)` outcome scale. No percentage variance reduction is computed
  in this arm at all -- that needs a random-intercept-only refit series against
  a single Model-1 baseline, which this ladder does not produce. Deliberate gap.
- **The two windows are different measures, not a longer one.** WPS-view counts
  (2011-2021) run 2-3x establishments-view counts (2011-2019) and correlate
  ~0 from 2017 on.

## Reporting scope (PI direction, 2026-09-11)

Reporting focus has moved to the **WPS view** (2011-2021). The establishments
view covers pesticide **producers, sellers and distributors** rather than the
WPS-protected agricultural operations this paper is about, so it is no longer
the outcome the team writes up, and the new stepwise arm is **WPS-only**.

The two 2011-2019 establishments-view cells are **kept in this memo**. They are
the record of what was actually fit, and the validator checks them; deleting
them would make the ladder, the family-selection table and the matched
zero-inflation tallies unreproducible from what is printed here. Read them as
the record, not as the reported results.

## The binding constraint: zeros

A mirrored zero-inflation block at Model 3 carries up to 10 logistic
parameters. Only one cell has the zeros to identify them.
"""

MEMO_METHOD = """
## Specification

```
conditional:  count ~ time + time2 + time3 [+ log_inspections]
                      + SPEND_APP_z + SPEND_WORK_z + lii_2017_z
                      + h2a_per_farmworker_z + dol_demand_met_pct_z + pct_flc_z
                      + (1 | state) + (1 | year)

zero-infl.:        ~ the richest estimable subset of the same predictors
```

`glmmTMB`, ML, `time = year - 2017`. **There is no random slope anywhere in
this arm and no random-effects fallback tier**: a family that fails at
`(1 | state) + (1 | year)` is reported as non-converged and excluded from
selection, never downgraded to a simpler structure.

The fixed cubic and `(1 | year)` deliberately coexist (PI direction). `time` is
an exact function of `year`, so the cubic is the smooth component and the year
random intercept the shrunk departure from it. Two consequences are reported
rather than hidden: the cubic can lose significance to the year effect, and
**sigma^2_year rests on 9 (2019) or 11 (2021) levels** -- at or below the
conventional minimum for a variance component. No claim here rests on
sigma^2_year alone.

**COVID is not fit as an indicator.** `(1 | year)` absorbs the pandemic shock
by construction, so a 2020-21 dummy would compete with the term that already
contains it. The 2020 and 2021 year BLUPs are reported instead. They are **not**
comparable to the other arms' COVID coefficients.

### Zero-inflation tier ladder

ZI predictors are always a **subset** of the conditional predictors. That keeps
one analytic sample per (cell, model), which is what makes AIC comparable
across tiers. Within a family the ladder takes the richest tier that converges
cleanly (a fidelity rule, not an AIC rule); across families AIC picks the
winner, with each competitor's tier shown.
"""


def write_memo(r, sel, coef, var, tally):
    parts = [MEMO_HEADER]

    zt = []
    for cell in CELLS:
        v = r[f'{cell}__M3__{r[f"{cell}__meta"]["m3_winner"]}']
        zt.append(f'| {CELL_LABEL[cell]} | {v["n_obs"]} | {int(v["obs_zeros"])} '
                  f'| {100 * v["obs_zeros"] / v["n_obs"]:.1f}% '
                  f'| {ZI_TIER_LABEL.get(v.get("zi_tier_reached"), "n/a (plain family)")} |')
    parts.append('\n| Cell | N | Zeros | % | ZI tier reached by the selected family |\n'
                 '|---|---:|---:|---:|---|\n' + '\n'.join(zt) + '\n')
    parts.append(MEMO_METHOD)

    # --- selection ---
    parts.append('\n## Family selection\n\nLowest AIC among converged, '
                 'non-degenerate, non-collapsed fits at Model 3. Winners are '
                 'chosen **independently per cell** -- the two outcomes may '
                 "select different families, which per the PI's retraction of "
                 'the symmetry rationale is an expected result, not a defect.\n')
    m3 = sel[sel.model == 'M3'].copy()
    lines = ['| Cell | Family | AIC | dAIC to winner | ZI tier | Eligible |',
             '|---|---|---:|---:|---|---|']
    for cell in CELLS:
        sub = m3[m3.cell == cell].sort_values('aic', na_position='last')
        for _, row in sub.iterrows():
            mark = ' **(selected)**' if row.is_winner else ''
            aic = f'{row.aic:.2f}' if pd.notna(row.aic) else 'non-conv.'
            d = f'{row.delta_aic_to_winner:+.2f}' if pd.notna(row.delta_aic_to_winner) else '--'
            why = ('degenerate' if row.zi_degenerate else
                   f'collapsed to {row.collapsed_to}' if row.collapsed_to else
                   'yes' if row.eligible else 'no')
            tier = row.zi_tier_reached if isinstance(row.zi_tier_reached, str) else '--'
            lines.append(f'| {CELL_LABEL[cell]} | {row.family_label}{mark} | {aic} '
                         f'| {d} | {tier} | {why} |')
    parts.append('\n'.join(lines) + '\n')

    stab = ['| Cell | Model 1 winner | Model 3 winner | Stable |', '|---|---|---|---|']
    for cell in CELLS:
        m = r[f'{cell}__meta']
        stab.append(f'| {CELL_LABEL[cell]} | {FAMILY_LABEL[m["m1_winner"]]} '
                    f'| {FAMILY_LABEL[m["m3_winner"]]} | {"yes" if m["stable"] else "**no**"} |')
    parts.append('\n### Does the winner change as covariates enter?\n\n'
                 + '\n'.join(stab) + '\n')

    # --- ZI strength ---
    parts.append('\n## Strength of the zero-inflated specifications\n\n'
                 'Matched comparisons only: same cell, same model, same analytic '
                 'sample, both converged, neither degenerate nor collapsed. A '
                 'positive margin means the zero-inflated family wins.\n')
    if len(tally):
        agg = (tally.groupby(['zi_family_label', 'plain_family_label'])
               .agg(n=('zi_wins', 'size'), wins=('zi_wins', 'sum'),
                    min_margin=('margin', 'min'), max_margin=('margin', 'max'))
               .reset_index())
        tl = ['| ZI family | vs. plain family | Record | AIC margin range |',
              '|---|---|---|---|']
        for _, a in agg.iterrows():
            tl.append(f'| {a.zi_family_label} | {a.plain_family_label} '
                      f'| {int(a.wins)}-{int(a.n - a.wins)} '
                      f'| {a.min_margin:+.2f} to {a.max_margin:+.2f} |')
        parts.append('\n'.join(tl) + '\n')
        own = tally[tally.is_own_counterpart]
        parts.append(f'\nAgainst its **own** negative-binomial counterpart '
                     f'(the comparison that isolates inflation while holding the '
                     f'parameterisation fixed), a zero-inflated family wins '
                     f'**{int(own.zi_wins.sum())} of {len(own)}** matched '
                     f'comparisons. This arm fits ZI-NB1 rungs, which the previous '
                     f'ladder did not, so an NB1 win is now tested against its own '
                     f'zero-inflated counterpart rather than winning by default.\n')
    else:
        parts.append('\n**No matched comparison was available in any cell.** Every '
                     'zero-inflated fit either failed to converge at '
                     '`(1 | state) + (1 | year)`, was ZI-boundary-degenerate, or '
                     'collapsed onto a plain twin. That is the reportable result.\n')

    # --- Jafari Table 5 blocks ---
    parts.append(how_to_read(r))
    parts.append('\n## Model 3, Jafari Table 5 format\n\n'
                 'Significance: `***` p<.001, `**` p<.01, `*` p<.05, `+` p<.10. '
                 'This is the project convention and differs in rendering from '
                 "Jafari's own legend; the two tables should not be read against "
                 'each other on stars alone. An em dash in the zero-inflated block '
                 'means the term was **absent from the ZI formula** at the tier '
                 'reached, not estimated at zero.\n\n'
                 '`b (SE)` is the **raw coefficient** -- log scale in the '
                 'conditional block, logit scale in the zero-inflation block. '
                 '`exp(b)` is an **incidence rate ratio** in the conditional block '
                 'and an **odds ratio on being a structural zero** in the '
                 'zero-inflation block; the two are not interchangeable. See '
                 '"How to read these two blocks" above.\n')
    for cell in CELLS:
        parts.append(jafari_table(r, cell))

    # --- variance ---
    parts.append('\n## Variance components (selected family, log link)\n')
    vl = ['| Cell | Family | sigma^2_state | sigma^2_year | sigma^2_ZI,state '
          '| Dispersion | Obs. zeros | Exp. zeros |', '|---|---|---:|---:|---:|---:|---:|---:|']
    for _, row in var.iterrows():
        f = lambda x: '--' if pd.isna(x) else f'{x:.4f}'
        vl.append(f'| {CELL_LABEL[row.cell]} | {row.family_label} '
                  f'| {f(row.sigma2_state)} | {f(row.sigma2_year)} '
                  f'| {f(row.sigma2_zi_state)} | {f(row.dispersion)} '
                  f'| {int(row.obs_zeros)} | {row.exp_zeros:.2f} |')
    parts.append('\n'.join(vl) + '\n')
    parts.append('\n`Dispersion` is theta for NB2 and a multiplier for NB1 -- **not** a '
                 'residual variance. `sigma2_e` is null for every count fit here, '
                 'deliberately.\n')

    zrows = var[var.pr_structural_zero_sample_mean.notna()]
    if len(zrows):
        zl = ['| Cell | ZI tier | Pr(structural 0), **sample mean** | Obs. zero rate '
              '| Pr at median state | Pr marginal over u |',
              '|---|---|---:|---:|---:|---:|']
        for _, row in zrows.iterrows():
            fmt = lambda x: 'n/a' if pd.isna(x) else f'{x:.4f}'
            zl.append(f'| {CELL_LABEL[row.cell]} | {row.zi_tier_reached} '
                      f'| **{row.pr_structural_zero_sample_mean:.4f}** '
                      f'| {row.obs_zeros / row.n_obs:.4f} '
                      f'| {fmt(row.pr_structural_zero_median_state)} '
                      f'| {fmt(row.pr_structural_zero_marginal)} |')
        parts.append(
            '\n### Structural-zero probability\n\n'
            'The **sample mean** is the reportable figure: the mean over the analytic '
            'sample of each state-year\'s own zero-inflation probability, conditional '
            'on the fitted random effects. It is comparable to the observed zero rate '
            'beside it, because structural zeros are a subset of all zeros.\n\n'
            'The last two columns are `plogis(b0)` and the Gauss-Hermite marginal '
            '`E[plogis(b0 + u)]`, and they are **n/a wherever the ZI block carries '
            'covariates** -- which under a mirrored ZI formula is most cells. Both '
            'evaluate the ZI linear predictor at x = 0, and with `log_inspections` '
            '(sample mean ~3.5, never z-scored) in the ZI block, x = 0 describes no '
            'state in the data. Computing them anyway is how an earlier draft of this '
            'memo reported a 0.46 structural-zero probability for a cell whose own '
            'model simulates 78 zeros in 501 rows. They are reported only at the '
            '`intercept` tier, where b0 is the entire ZI linear predictor.\n\n'
            + '\n'.join(zl) + '\n')

    # --- year effects, replacing COVID ---
    yl = ['| Cell | sigma^2_year | 2020 BLUP | 2021 BLUP |', '|---|---:|---:|---:|']
    for _, row in var.iterrows():
        f = lambda x: '--' if pd.isna(x) else f'{x:+.4f}'
        yl.append(f'| {CELL_LABEL[row.cell]} | {row.sigma2_year:.3e} '
                  f'| {f(row.year_blup_2020)} | {f(row.year_blup_2021)} |')
    parts.append('\n## Year random effects (in place of a COVID indicator)\n\n'
                 'On the log link; negative means fewer events than the cubic trend '
                 'predicts. The 2019-window cells have no 2020/2021 rows. These are '
                 '**not** comparable to the COVID coefficients in the other arms.\n\n'
                 + '\n'.join(yl) + '\n')

    with open(DOCS + 'jafari_crossed_models.md', 'w') as fh:
        fh.write('\n'.join(parts))


def main():
    r = load()
    sel = selection_table(r)
    coef = coefficient_table(r)
    var = variance_table(r)
    tally = zi_strength_tally(r)
    sel.to_csv(GEN + 'jafari_crossed_selection.csv', index=False)
    coef.to_csv(GEN + 'jafari_crossed_coefficients.csv', index=False)
    var.to_csv(GEN + 'jafari_crossed_variance.csv', index=False)
    tally.to_csv(GEN + 'jafari_crossed_zi_strength.csv', index=False)
    write_memo(r, sel, coef, var, tally)
    print(f'wrote jafari_crossed_selection.csv    ({len(sel)} rows)')
    print(f'wrote jafari_crossed_coefficients.csv ({len(coef)} rows)')
    print(f'wrote jafari_crossed_variance.csv     ({len(var)} rows)')
    print(f'wrote jafari_crossed_zi_strength.csv  ({len(tally)} rows)')
    print('wrote docs/jafari_crossed_models.md')


if __name__ == '__main__':
    main()
